language: elixir
matrix:
  include:
    - otp_release: 20.0
      elixir: 1.6
    - otp_release: 21.0
      elixir: 1.7
sudo: false
script:
  - mix test
notifications:
  recipients:
    - diego@curbelo.com
